---
title: "Introduction to R Syntax"
output: html_notebook
---

# Calculations
Let’s start with the basic syntax for mathematical calculations in R. R performs addition, subtraction, multiplication
and division with `*` `-` `+` `/`.

An example is given below:

```{R}
# Results in "500"
573 - 74 + 1

# Results in "50"
25 * 2

# Results in "2"
10 / 5
```
Mathematical operations in R follow the standard mathematical order of operations.

Calculate the result of this equation: `25 * 4 + 9 / 3` in the R code block in your R-markdown file. 
A code block has been initialised for you below to insert the equation. 

```{R}

```

Check your answer:

```{R}
25 * 4 + 9 / 3
```

# Comments
Text written in a program but not run by the computer is called a comment. R interprets anything after a `#` as a comment.
It is good practice to add comments explaining briefly what the code does, what input it requires, or your thought 
process behind the code. When you revisit the code months down the road, you will thank yourself. 

Furthermore, comments can be placed in code blocks to 'deactivate' that line of code. The following illustrates this:

```{R}
for(i in seq(1:10)){
  i <- i + 2
  print(i)
}
```

Now add a comment to the line `i <- i +2` to disable the line of code and check the output. 

# Data Types
Let’s dive into how R “thinks about” different types of data. In R and in programming, data types are the classifications 
we give different kinds of information pieces. In this lesson, we will explore the following R data types:

| * Numeric: Any number with or without a decimal point: 23, 0.03and the numeric null value NA.
| * Character: Any grouping of characters on your keyboard (letters, numbers, spaces, symbols, etc.) or text.
|              Most strings are surrounded by single quotes: ' ... ' or double quotes " ... ". 
|              Sometimes you will hear this type referred to as “string.”
| * Logical: This data type only has two possible values— either TRUE or FALSE (without quotes). It’s helpful to think
|            of logical types or booleans as on and off switches or as the answers to a “yes” or “no” question.
| * Vectors: A list of related data that is all the same type.
| * NA: This data type represents the absence of a value, and is represented by the keyword NA (without quotes) 
|       but it has its own significance in the context of the different types. That is there is a numeric NA,
|       a character NA,and a logical NA.

